-- 1. Create Tables FIRST
create table if not exists rooms (
  room_id text primary key,
  password text not null,
  participants text[] default '{}',
  status text default 'waiting',
  created_at timestamptz default now(),
  expires_at timestamptz
);

create table if not exists messages (
  id bigint generated by default as identity primary key,
  room_id text references rooms(room_id) on delete cascade,
  text text not null,
  sender text not null,
  created_at timestamptz default now()
);

-- 2. Enable RLS
alter table rooms enable row level security;
alter table messages enable row level security;

-- 3. Create Policies
-- Room Policies
create policy "Anyone can create a room" on rooms for insert to anon, authenticated with check (true);
create policy "Anyone can view rooms" on rooms for select to anon, authenticated using (true);
create policy "Participants can update rooms" on rooms for update to anon, authenticated using (true);
create policy "Participants can delete rooms" on rooms for delete to anon, authenticated using (true);

-- Message Policies
create policy "Anyone can insert messages" on messages for insert to anon, authenticated with check (true);
create policy "Anyone can view messages" on messages for select to anon, authenticated using (true);

-- 4. Setup Realtime (MUST be done AFTER tables exist)
drop publication if exists supabase_realtime;
create publication supabase_realtime for table rooms, messages;
